  gitea-server:
    image: gitea/gitea
    container_name: gitea_server
    ports:
      - 3000:3000
      - 222:22
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - SSH_PORT=222
      - DB_TYPE=postgres
      - DB_HOST=db:5432
      - DB_NAME=${POSTGRES_DATABASE}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWD=${POSTGRES_PASSWORD}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timzone:/etc/timezone:ro
      - ./gitea:/data
    networks:
      - gitea
    depends_on:
      - db
  db:
    image: postgres
    container_name: postgres_gitea
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgressql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PG_DATA=/var/lib/postgresql/data
    networks:
      - gitea
